class DatabaseAlreadyOpenException implements Exception{}
class CouldNotDeleteUserException implements Exception{}
class UnableToGetDocumentsDirectoryException implements Exception{}
class UserAlreadyExistsException implements Exception{}
class UserDoesNotExistsException implements Exception{}
class DatabaseIsNotOpenException implements Exception{}
class CouldNotDeleteNoteException implements Exception{}
class NoteDoesNotExistsException implements Exception{}
class CouldNotUpdateNoteException implements Exception{}
class UserShouldBeSetBeforeReadingAllNotes implements Exception{}